# Generated by Django 6.0.2 on 2026-02-27 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_matiere', models.CharField(choices=[('base', 'Matière première'), ('premix', 'Premix / Additif')], default='base', max_length=20)),
                ('stock_actuel', models.FloatField(default=0)),
                ('stock_minimum', models.FloatField(default=0)),
                ('unite', models.CharField(default='tonnes', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('gamme', models.CharField(choices=[('pondeuse', 'Gamme Pondeuse'), ('chair', 'Gamme Chair'), ('concentre', 'Gamme Concentré'), ('ruminant', 'Gamme Ruminant')], max_length=50)),
                ('sous_gamme', models.CharField(choices=[('poulette_demarrage', 'Poulette démarrage 0-8 semaines'), ('poulette_finition', 'Poulette finition 8-18 semaines'), ('pre_ponte', 'Poulette pré-ponte 18-21 semaines'), ('pondeuse_22_50', 'Pondeuse 22-50 semaines'), ('pondeuse_50_90', 'Pondeuse 50-90 semaines'), ('prestarter', 'Prestarter 0-7 jours'), ('chair_demarrage', 'Chair démarrage 7-21 jours'), ('chair_finition', 'Chair finition 21-35 jours'), ('concentre_20_pondeuse', 'Concentré 20% pondeuse'), ('concentre_30_chair', 'Concentré 30% chair'), ('concentre_2_5_pondeuse', 'Concentré 2,5% pondeuse'), ('vache_laitiere_18', 'Vache laitière 18%'), ('super_embouche', 'Super embouche'), ('super_ruminant_entretien', 'Super ruminant entretien')], max_length=100)),
                ('stock_actuel', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_a_produire', models.FloatField(help_text='Quantité en tonnes')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('termine', 'Terminé')], default='attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('quantite', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.matierepremiere')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
        ),
        migrations.CreateModel(
            name='LotProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=50, unique=True)),
                ('quantite_produite', models.FloatField()),
                ('date_production', models.DateTimeField(auto_now_add=True)),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.ordrefabrication')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('destination', models.CharField(max_length=200)),
                ('date_livraison', models.DateField()),
                ('statut', models.CharField(choices=[('prepare', 'Préparée'), ('livre', 'Livrée'), ('retour', 'Retour')], default='prepare', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.client')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.lotproduction')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.FloatField(help_text='Ex: 60 = 60%')),
                ('matiere_premiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.matierepremiere')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.produit')),
            ],
        ),
    ]
