# Generated by Django 6.0.2 on 2026-02-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotproduction',
            name='produit',
        ),
        migrations.AddField(
            model_name='lotproduction',
            name='rendement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotproduction',
            name='temps_production_heures',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.lotproduction'),
        ),
        migrations.AlterField(
            model_name='lotproduction',
            name='ordre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='production.ordrefabrication'),
        ),
        migrations.CreateModel(
            name='RetourProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('motif', models.TextField()),
                ('date_retour', models.DateField(auto_now_add=True)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.livraison')),
            ],
        ),
    ]
